### PR TITLE
Remove arrow version specific test data.

### PR DESCRIPTION
**Pull request by pearu**

### CODE REVIEW

**Comment by andrewseidl** [comment]
Looks like it's failing the style checks, otherwise looks good (or will be once we move everything to 0.10.0):

```
$ flake8
./tests/test_ipc.py:13:1: E302 expected 2 blank lines, found 1
./tests/test_ipc.py:16:36: E231 missing whitespace after ','
./tests/test_ipc.py:16:39: E231 missing whitespace after ','
./tests/test_ipc.py:16:47: E231 missing whitespace after ','
./tests/test_ipc.py:17:37: E231 missing whitespace after ','
./tests/test_ipc.py:17:40: E231 missing whitespace after ','
./tests/test_ipc.py:17:48: E231 missing whitespace after ','
./tests/test_ipc.py:27:1: E305 expected 2 blank lines after class or function definition, found 1
./tests/test_ipc.py:31:1: E302 expected 2 blank lines, found 1
```

**Comment by andrewseidl** [comment]
Hopefully the final issue :)

Looks like we'll need to pin the version of Arrow at https://github.com/mapd/pymapd/blob/05801e23a2aad44c17d2510190ba8754fa179460/conda-recipes/pymapd/meta.yaml#L24-L33

Without it, that `conda build` is attempting to install the newer version of Arrow but still attempting to link to the older libarrow:

```
ImportError: libarrow.so.0: cannot open shared object file: No such file or directory
```

**Comment by pearu** [comment]
Good catch. I'll try the following fix soon:
```
   - arrow-cpp >=0.10.0 
   - pyarrow >=0.10.0 
```

**Comment by pearu** [comment]
Although, the proposed changes in unittests (pure Python, build independent) should not have broken the CI build.

**Comment by andrewseidl** [comment]
Still pulling in 0.10.0. Maybe have to pin directly to `0.7.1` instead of `>= 0.7.1`?

**Comment by andrewseidl** [comment]
Thanks!

**Pull request merged**
