### PR TITLE
WIP Direct loading of Arrow columnar memory to MapD

### PR DESCRIPTION
**Pull request by wesm**
Needs https://github.com/mapd/mapd-core/pull/93

Still some things to do over here:

- [ ] sanitize Arrow column types to match existing MapD table metadata 
- [ ] verify that data was loaded correctly
- [x] test perf vs. load_table_binary_columnar

### CODE REVIEW

**Comment by wesm** [comment]
Initial perf test in a release MapD build

setup (this is 3x more data than #50):

```
import pandas as pd
import numpy as np
import pymapd

N = 3_000_000
df = pd.DataFrame(np.random.randn(N, 4), columns=list('abcd'))
df['a'] = df['a'].astype('int32')
data = list(df.itertuples(index=False))

con = pymapd.connect(user='mapd', password='HyperInteractive', host='localhost', dbname='mapd')
con.execute("DROP TABLE IF EXISTS foo;")
con.execute("CREATE TABLE foo (a int, b double, c double, d double);")
```

tuple-based load:

```
%time con.load_table('foo', data)
CPU times: user 37.4 s, sys: 888 ms, total: 38.3 s
Wall time: 42.5 s
```

Arrow-based load:

```
%time con.load_table_arrow('foo', df)
CPU times: user 264 ms, sys: 16 ms, total: 280 ms
Wall time: 421 ms
```

From the benchmarks in #50 this looks to be about 10x faster than the Thrift-based load_columnar path. I couldn't get it working, though, maybe it has something to do with the updated Thrift bindings (thrift 0.10.0 across the board)

```
%time con.load_table_columnar('foo', df)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<timed eval> in <module>()

~/code/goai/pymapd/pymapd/connection.py in load_table_columnar(self, table_name, data, preserve_index)
    416             raise TypeError("Unknown type {}".format(type(data)))
    417         self._client.load_table_binary_columnar(self._session, table_name,
--> 418                                                 input_cols)
    419 
    420     def load_table_arrow(self, table_name, data, preserve_index=False):

~/code/goai/pymapd/mapd/MapD.py in load_table_binary_columnar(self, session, table_name, cols)
   1578          - cols
   1579         """
-> 1580         self.send_load_table_binary_columnar(session, table_name, cols)
   1581         self.recv_load_table_binary_columnar()
   1582 

~/code/goai/pymapd/mapd/MapD.py in send_load_table_binary_columnar(self, session, table_name, cols)
   1587         args.table_name = table_name
   1588         args.cols = cols
-> 1589         args.write(self._oprot)
   1590         self._oprot.writeMessageEnd()
   1591         self._oprot.trans.flush()

~/code/goai/pymapd/mapd/MapD.py in write(self, oprot)
   8160     def write(self, oprot):
   8161         if oprot._fast_encode is not None and self.thrift_spec is not None:
-> 8162             oprot.trans.write(oprot._fast_encode(self, (self.__class__, self.thrift_spec)))
   8163             return
   8164         oprot.writeStructBegin('load_table_binary_columnar_args')

TypeError: spec is not a tuple
```

Out of this 420ms, here is the cProfile that I see:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
      8/1    0.000    0.000    0.421    0.421 {built-in method builtins.exec}
        1    0.000    0.000    0.421    0.421 <string>:1(<module>)
        1    0.000    0.000    0.421    0.421 connection.py:420(load_table_arrow)
        1    0.000    0.000    0.333    0.333 MapD.py:1608(load_table_binary_arrow)
        1    0.000    0.000    0.268    0.268 MapD.py:1618(send_load_table_binary_arrow)
        1    0.000    0.000    0.176    0.176 MapD.py:8308(write)
        2    0.163    0.081    0.163    0.081 {built-in method thrift.protocol.fastbinary.encode_binary}
        2    0.000    0.000    0.092    0.046 TTransport.py:173(flush)
        2    0.000    0.000    0.092    0.046 TSocket.py:135(write)
        2    0.092    0.046    0.092    0.046 {method 'send' of '_socket.socket' objects}
        1    0.000    0.000    0.075    0.075 _pandas_loaders.py:115(_serialize_arrow_payload)
        2    0.000    0.000    0.066    0.033 TBinaryProtocol.py:133(readMessageBegin)
        6    0.000    0.000    0.066    0.011 TBinaryProtocol.py:216(readI32)
        8    0.000    0.000    0.066    0.008 TTransport.py:56(readAll)
        8    0.000    0.000    0.066    0.008 TTransport.py:157(read)
        2    0.000    0.000    0.066    0.033 TSocket.py:115(read)
        2    0.066    0.033    0.066    0.033 {method 'recv' of '_socket.socket' objects}
        1    0.000    0.000    0.065    0.065 MapD.py:1628(recv_load_table_binary_arrow)
        1    0.000    0.000    0.039    0.039 {built-in method from_pandas}
        1    0.000    0.000    0.039    0.039 pandas_compat.py:206(dataframe_to_arrays)
        4    0.038    0.010    0.038    0.010 {pyarrow.lib.from_pandas}
        1    0.023    0.023    0.023    0.023 {method 'write_batch' of 'pyarrow.lib._RecordBatchWriter' objects}
       10    0.000    0.000    0.013    0.001 TTransport.py:164(write)
       10    0.013    0.001    0.013    0.001 {method 'write' of '_io.BytesIO' objects
```

So this suggests that you could go even faster by doing your Thrift comms in C++ instead of Python (like https://github.com/cloudera/hs2client).

I'll add some tests to handle obvious type casts (e.g. double->float, or int64 -> smaller integers) but maybe hand this over to @TomAugspurger to do further integration testing

**Comment by tmostak** [comment]
Hi @wesm this is awesome. You might try benchmarking with temporary tables (CREATE TEMPORARY TABLE) to eliminate overhead of persisting on disk to get an even more isolated test.

**Comment by wesm** [comment]
Cool, that shaved about 30ms off the runtime. It seems the majority of the time is now being spent in Thrift-Python inside the Thrift protocol. about 20% of the time is converting from pandas.DataFrame to a serialized Arrow payload

**Comment by TomAugspurger** [comment]
Thanks @wesm taking a look now. I'll probably just push additional commits directly to this branch if that's OK with you.

**Comment by wesm** [comment]
Be my guest

**Comment by TomAugspurger** [comment]
> I couldn't get it working, though, maybe it has something to do with the updated Thrift bindings (thrift 0.10.0 across the board)

I couldn't get the arrow loader to work with the bindings you generated. In 83c6cc3 I included instructions for how I generate them (it's a bit more than a `thrift gen-py`). Anyway, I can more or less collaborate your performance numbers:

```python
In [2]: %time con.load_table('foo', data)
   ...:
CPU times: user 41.6 s, sys: 2.48 s, total: 44 s
Wall time: 53.3 s

In [5]:  %time con.load_table_columnar('foo', df, preserve_index=False)
CPU times: user 1.04 s, sys: 195 ms, total: 1.24 s
Wall time: 3.95 s

In [8]: %time con.load_table_arrow('foo', df)
   ...:
CPU times: user 339 ms, sys: 211 ms, total: 549 ms
Wall time: 1.27 s
```

So things look good! A bit slower than yours, but probably just hardware?

**Comment by TomAugspurger** [comment]
@wesm would you recommend `preserve_index=False` for the default? I wasn't sure which to go with.

**Comment by wesm** [comment]
I wasn't sure about that. If you're inserting into a database, then maybe more likely that the DataFrame columns are the same as the ones in the table you're loading, so the index may be a nuisance more often than a help

**Comment by wesm** [comment]
@TomAugspurger on your perf numbers, it is probably just hardware differences (I am on Xeon E3-1505M @ 2.8ghz), but

* Is MapD running inside a docker container or locally?
* Release vs. debug build of MapD?

**Comment by TomAugspurger** [comment]
>  If you're inserting into a database, then maybe more likely that the DataFrame columns are the same as the ones in the table you're loading, so the index may be a nuisance more often than a help

That was my thought as well. I'll change the defaults to all be False.

I'm on a 2.8 GHz i7. I noticed in another thread that your DataFrame -> pa.Table serialization numbers were quicker as well. MapD is a local debug build.

I'm updating the docs now and will add a few more tests for DataFrame and RecordBatches, then this should be good on pymapd's side. I'll keep an eye on https://github.com/mapd/mapd-core/pull/93

**Comment by wesm** [comment]
Gotcha. Doing a release build for MapD (`-DCMAKE_BUILD_TYPE=release`) will make things quicker. 

I'll wait for you to finish then I can add a few type casts and some tests probably later today; if you'd rather do this yourself no worries

**Comment by TomAugspurger** [comment]
OK, I think I'm all done for the moment. Summary of changes:

- regenerated thrift bindings
- refactored `load_table` to delegate to `load_table_arrow`, `load_table_columnar` (pandas), `load_table_rowwise` based on type
- moved some tests around. All the loader tests are under `tests/test_integration.py::TestLoaders` now.

Currently `pytest tests/test_integration.py::TestLoaders::test_load_empty_table_arrow --pdb` fails for me when checking the result. The write completes without error, but when I follow that up with a `select * from empty_table`, there are no results. I'll debug later today if I can.

> I'll wait for you to finish then I can add a few type casts and some tests probably later today

Would this be done on the client side? I saw that you queried the database for the table metadata, but didn't do anything with it yet. If it's on the client side, I can take care of making the data returned by `get_table_details` more useful.

**Comment by wesm** [comment]
> Would this be done on the client side?

Yeah, that's the easiest thing, since we can just use `pyarrow.Array.cast`

**Comment by tmostak** [comment]
Hi @TomAugspurger @wesm I'd love to demo this at my Strata talk on Wednesday. @TomAugspurger do you think it will be merged with a build by then? If not I can probably build the branch on my Mac/Ubuntu VM, whatever is easiest.

**Comment by TomAugspurger** [comment]
I'll merge this now (we'll in 10 minutes, once I make those two failing tests conditional on pymapd having Wes' `load_table_binary_arrow` endpoint). I'll open an issue for the remaining work (which I think is just auto-casting between type precisions when possible and necessary).

**Comment by TomAugspurger** [comment]
I may wait for @wesm's  thoughts on why

```python
pytest tests/test_integration.py::TestLoaders::test_load_empty_table_arrow
```

is failing. Hopefully a simple fix in https://github.com/mapd/mapd-core/pull/93 to ensure that the data is written correctly once the database has received the data.

**Comment by wesm** [comment]
I can investigate this tomorrow

**Comment by wesm** [comment]
Looking at this now

**Comment by wesm** [comment]
Fixed the unit test in https://github.com/mapd/mapd-core/pull/93/commits/c496b695a35c4414116bfd85d80df827678750f0

I'm going to address the code review feedback in that patch now, this PR can be merged either now or after I'm done there (I'll double check that the test suite here still passes)

**Comment by TomAugspurger** [comment]
I built your PR over in https://github.com/mapd/mapd-core/pull/93 and verified that the tests here all pass. I'll merge this now. Thanks!

**Pull request merged**
